version: '3.7'

services:
  graphDB:
    image: dhlabbasel/graphdb-free
    container_name: 'graphDB'
    volumes:
      - "./graphDB:/graphdb/data"
    ports:
      - 7200:7200

  web:
    build:
      context: web
      dockerfile: Dockerfile
    container_name: 'django'
    ports:
      - 8000:8000
    command: pipenv run python manage.py runserver 0.0.0.0:8000